apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: orders-dr
  namespace: mv100
spec:
  host: orders.mv100.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: orders-canary-dr
  namespace: mv100
spec:
  host: orders-canary.mv100.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
