---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: orders
  namespace: mv100
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  strategy:
    canary:
      stableService: orders
      canaryService: orders-canary
      trafficRouting:
        istio:
          virtualService:
            name: api-vs
            routes:
              - orders-route
      steps:
        - setWeight: 20
        - pause:
            duration: 30
        - setWeight: 50
        - pause:
            duration: 60
        - setWeight: 100
  template:
    metadata:
      labels:
        app: orders
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: orders
          image: devopsflow999/orders:test5
          ports:
            - containerPort: 3003
          env:
            - name: PGUSER
              value: appuser
            - name: PGPASSWORD
              value: appuser
            - name: PGDATABASE
              value: mv100db
            - name: PGHOST
              value: postgres-postgresql.kafka.svc.cluster.local
            - name: PGPORT
              value: "5432"
            - name: REDIS_URL
              value: redis://redis-master.kafka.svc.cluster.local:6379
            - name: KAFKA_BROKERS
              value: kafka.kafka.svc.cluster.local:9092
            - name: JWT_SECRET
              value: supersecretkey
            - name: STRIPE_SECRET_KEY
              value: sk_test_51RaNzg4TJHeKoXcgLvssqY3YO8ehdG3etb60ahEfAfC3KryGRvXzgKLCqwQB3zHkScJe6oiczRCuHDJtf658mqOa00rwmi2ON8
            - name: STRIPE_WEBHOOK_SECRET
              value: whsec_1ba82957afd637a76c2edbb4dd2edc84156f42dc046095e8ac64e50e7fe50f3c
            - name: PORT
              value: "3003"
            - name: CORS_ORIGIN
              value: https://frontend.localdev.me
