apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: catalog-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "{{ .Values.istio.host }}"
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.istio.prefix }}
      route:
        - destination:
            host: catalog.{{ .Values.namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
          weight: 100
