apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-frontend
  namespace: mv100
spec:
  metrics:
    - name: frontend-success-rate
      interval: 30s
      count: 3
      successCondition: result[0] > 0.99
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus.istio-system:9090
          query: |
            sum(rate(istio_requests_total{reporter="destination",destination_workload="frontend",response_code!~"5.*"}[1m]))
            /
            sum(rate(istio_requests_total{reporter="destination",destination_workload="frontend"}[1m]))
