apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: frontend-dr
  namespace: mv100
spec:
  host: frontend.mv100.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: frontend-canary-dr
  namespace: mv100
spec:
  host: frontend-canary.mv100.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
