apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: catalog-vs
  namespace: mv100
spec:
  hosts:
    - "api.localdev.me"
  gateways:
    - api-gateway
  http:
    - match:
        - uri:
            prefix: /catalog
      route:
        - destination:
            host: catalog.mv100.svc.cluster.local
            port:
              number: 3001
          weight: 100
