apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: cart-dr
  namespace: mv100
spec:
  host: cart.mv100.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: cart-canary-dr
  namespace: mv100
spec:
  host: cart-canary.mv100.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
