replicaCount: 1

image:
  repository: devopsflow999/catalog
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

env:
  PORT: "3001"
  PGUSER: "appuser"
  PGPASSWORD: "appuser"
  PGDATABASE: "mv100db"
  PGHOST: "postgres.mv100.svc.cluster.local"
  PGPORT: "5432"
  REDIS_URL: "redis://redis.mv100.svc.cluster.local:6379"
  KAFKA_BROKERS: "kafka.mv100.svc.cluster.local:9092"
  JWT_SECRET: "supersecretkey"
