apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: mv100
spec:
  selector:
    app: payments
  ports:
    - port: 3004
      targetPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: payments-canary
  namespace: mv100
spec:
  selector:
    app: payments
  ports:
    - port: 3004
      targetPort: 3004
