apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: auth-dr
  namespace: mv100
spec:
  host: auth.mv100.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: auth-canary-dr
  namespace: mv100
spec:
  host: auth-canary.mv100.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
