apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: api-gateway
spec:
  selector:
    {{- toYaml .Values.istio.gatewaySelector | nindent 4 }}
  servers:
    - port:
        number: {{ .Values.istio.port }}
        name: http
        protocol: HTTP
      hosts:
        - "{{ .Values.istio.host }}"
