replicaCount: 1

image:
  repository: devopsflow999/frontend
  tag: test21
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  VITE_API_AUTH: "http://auth.mv100.svc.cluster.local:3000"
  VITE_API_CATALOG: "http://catalog.mv100.svc.cluster.local:3001"
  VITE_API_CART: "http://cart.mv100.svc.cluster.local:3002"
  VITE_API_ORDERS: "http://orders.mv100.svc.cluster.local:3003"
  VITE_API_PAYMENTS: "http://payments.mv100.svc.cluster.local:3004"

istio:
  enabled: true
  gatewaySelector:
    istio: ingressgateway
  host: frontend.localdev.me
  port: 80
